#!/usr/bin/env bash
# Caddy: dump the live Caddyfile generated by caddy-docker-proxy (if available).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

if ! docker compose ps --status running --services 2>/dev/null | grep -qx caddy; then
  echo "ERROR: caddy is not running" >&2
  exit 1
fi

# caddy-docker-proxy stores generated config under /config or exposes via admin API
if docker compose exec -T caddy sh -c 'command -v caddy >/dev/null' 2>/dev/null; then
  docker compose exec -T caddy caddy adapt --config /config/caddy/Caddyfile.autosave 2>/dev/null \
    || docker compose exec -T caddy wget -qO- http://127.0.0.1:2019/config/ 2>/dev/null \
    || docker compose logs --no-color --tail=80 caddy
else
  docker compose logs --no-color --tail=80 caddy
fi
